// <auto-generated />
using System;
using CourseWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseWeb.Migrations
{
    [DbContext(typeof(CardContext))]
    [Migration("20240918155949_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CourseWeb.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NextId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Back = "Hello",
                            Front = "Привет",
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            Back = "World",
                            Front = "Мир",
                            Priority = 1
                        },
                        new
                        {
                            Id = 3,
                            Back = "Cat",
                            Front = "Кот",
                            Priority = 1
                        },
                        new
                        {
                            Id = 4,
                            Back = "Work",
                            Front = "Работа",
                            Priority = 1
                        },
                        new
                        {
                            Id = 5,
                            Back = "Home",
                            Front = "Дом",
                            Priority = 1
                        });
                });

            modelBuilder.Entity("CourseWeb.Models.Card", b =>
                {
                    b.HasOne("CourseWeb.Models.Card", "Next")
                        .WithMany()
                        .HasForeignKey("NextId");

                    b.Navigation("Next");
                });
#pragma warning restore 612, 618
        }
    }
}
